---
title: "Recent talks"
---
<br>

1. #### *Inference and the structure of mental representation* 
17th Congress on Logic, Methodology and Philosophy of Science and Technology, Buenos Aires, Argentina, August 2023. 

2. #### *Logic as a normative model of reasoning* 
(With Matteo De Benedetto)
Workshop "Models of Reasoning and Normativity" , Ruhr-Universität-Bochum, June 2023. 

3. #### *From Logical Form to the Form of Concepts* 
Symposium on Conceptual Spaces. Munich Center for Mathematical Philosophy, LMU, June 2023

4. #### *Variability, Correlations and Conceptual Coherence* 
Workshop: Conceptual Spaces at Work, Warsaw University of Technology, Warsaw, June 2023.

5. #### *From feature correlations to conceptual coherence* 
Workshop: The Cognitive and Ontological Dimensions of Naturalness, Heinrich- Heine-Universität Düsseldorf, May 2023.

6. #### *The role of categorization in inductive reasoning.* 
BAPS Invited Symposium: Categorization across fields, 2023 International Convention of Psychological Science (ICPS), Brussels, March 2023.

7. #### *Conceptos, Lenguaje, e Inferencia Racional* 
Workshop sobre Inferencia. Universidad Nacional de Córdoba, November 2022. 

8. #### *Local and global prperties of concepts: a metacognitive perspective* 
Seniorprofessur Gerhard Schurz – WS 2022/2023. Heinrich Heine Universität Dusseldorf, October 2022.

9. #### *From Logical Form to the Form of Concepts* 
Symposium on Conceptual Spaces. Munich Center for Mathematical Philosophy, LMU, June 2023

10. #### *Generic expressions and the structure of concepts* 
Workshop: Concepts: Philosophical Perspectives. Ruhr Universität Bochum, October 2022.


11. #### *Local and global prperties of concepts: a metacognitive perspective* 
Workshop *Conceptual Spaces and Social Spaces*,  Université Paris Cite ́, France, July 2022.
