---
title: "Teaching "
---

* Philosophy of the social sciences (undegraduate course, 60hs), University of the Republic, 2023.
* Formal methods in Philosophy of Science (graduate course, 30hs), University of the Republic, 2023.
* The implicit mind: theoretical and practical issues  (graduate course, 30hs), University of the Republic, 2022.
* Reasoning, normativity, and cognitive biases (postgraduate course, 30hs), Ruhr-Universität Bochum, 2022.
* Theories of concepts (graduate course, 30hs), University of the Republic, 2021.
* Theories of Reasoning (graduate seminar, 40hs), Ludwig-Maximilians Universität, 2020.
* Épistémologie  (undergraduate course, 45hs), Université Paris 1 Panthéon-Sorbonne,  2018-19.
* History and philosophy of science II  (undergraduate course, 60hs), University of the Republic, 2010-14, 2017, 2019, 2020, 2021.
* Philosophical foundations of cognitive science  (graduate course, 30hs), University of the Republic, 2019.
* Historical epistemology (undergraduate seminar), University of the Republic, 2017.
* Methods in philosophical research (undergraduate course, 30hs), University of the Republic,  2015, 2016.
* Introduction to epistemology (undergraduate course, 90hs), University of the Republic, 2012.
* Logic I (undergraduate course, 30hs), University of the Republic, 2009, 2010, 2011.